package error

const (
	// OK
	ERR_CODE_OK = 0

	// SYSTEM ERROR CODE
	ERR_CODE_SYS = 1000
	// TODO: ADD OTHER NEW SYSTEM ERROR, see auth error as example
	ERR_CODE_IO = 1001

	// DATABASE ERROR CODE
	ERR_CODE_DB = 1100
	// TODO: ADD OTHER NEW DATABASE ERROR, see auth error as example

	// NETWORK ERROR CODE
	ERR_CODE_NETWORK = 1200
	// TODO: ADD OTHER NEW NETWORK ERROR, see auth error as example

	// PARAMETER ERROR CODE
	ERR_CODE_PARA = 1300
	// TODO: ADD OTHER NEW PARAMETER ERROR,
	ERR_CODE_FILE_TOO_LARGE = 1301

	// AUTH ERROR CODE
	ERR_CODE_AUTH = 1400
	// TODO: ADD OTHER NEW AUTH ERROR, AFTER ERR_CODE_AUTH_EXPIRED AS BELOW
	ERR_CODE_AUTH_EXPIRED = 1401

	ERR_CODE_CONVERT      = 3000
	ERR_CODE_CONVERT_NIL  = 2001
	ERR_CODE_CONVERT_TYPE = 2000

	ERR_CODE_APPID_EXIST = 4000
	ERR_CODE_APPID_NOT_EXIST = 4001
	ERR_CODE_TIMEOUT         = 4002
	ERR_CODE_IMAGE_EXIST = 4003
	ERR_CODE_NAME_ILLEGAL = 4004

	// UNKNOWN ERROR
	// ERR_CODE_UNKNOWN = 1900
	// TODO: ADD OTHER NEW UNKNOW ERROR, see auth error as example
)
